[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && NODE_OPTIONS=--max-old-space-size=800 npx tsx src/server.ts"
