[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node --max-old-space-size=512 $(which tsx) src/server.ts"
