[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx tsc --skipLibCheck || true"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node dist/server.js"
